# Generated by Django 5.1.5 on 2025-01-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_emailconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfig",
            name="host",
            field=models.CharField(default="smtp.gmail.com", max_length=128),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
