"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import logging

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v!i4&$1af_0kqum=n2x*(+%et6a*7+398ww)^=hznm*!5%==g_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


load_dotenv()

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")


logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(levelname)s %(message)s",
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stock',
    'employees',
    'website',
]

JAZZMIN_SETTINGS = {
    # Título de la pestaña del navegador (HTML <title>)
    "site_title": "Mi Admin",

    # Título en la cabecera principal del Admin
    "site_header": "Proyecto Django",

    # Texto de bienvenida al entrar (login)
    "welcome_sign": "Bienvenido al Panel de Administración",

    # Nombre de la 'marca' o 'empresa' en la esquina superior izquierda
    "site_brand": "Mi Empresa",

    # Logo para usar en la cabecera (colócalo en static y dale la ruta aquí)
    # "site_logo": "images/logo.png",

    # Cambiar el tema (plantilla de Bootstrap). Opciones: cerulean, cosmo, cyborg, flatly, etc.
    # Ver más opciones aquí: https://bootswatch.com/


    # Opcional: Cambiar el ancho del panel lateral (px, rem o %)
    "navigation_expanded": True,

    # Cambiar el icono del sitio (favicon) si quieres
    # "site_icon": "images/favicon.ico",

    # Definir la lógica de menú
    # Por ejemplo, reorganizar apps, añadir secciones, íconos de FontAwesome, etc.
    "order_with_respect_to": ["employees", "stock", "auth", "admin", ],

    # Agregar enlaces rápidos en el panel lateral
    "custom_links": {
        "employees": [  # App label
            {
                "name": "Ver Fichajes Hoy",
                "url": "employees:fichajes_list",  # nombre de tu URL en la app
                "icon": "fas fa-list",  # icono FontAwesome
                "permissions": ["employees.view_fichaje"],
            },
        ],
    },

    # Opcional: Sobrescribir las apps o modelos para renombrarlos en el Admin
    "icons": {
        "employees.Empleado": "fas fa-user",
        "employees.Fichaje": "fas fa-clock",
        "stock.Producto": "fas fa-utensils",
    },

    # Mostrar el link "Ir al sitio" en el menú superior
    "show_home_link": True,

    # Mostrar el link "Cambiar contraseña" en el menú superior
    "show_change_password": True,

    # Mostrar el link "Cerrar sesión" en el menú superior
    "show_logout": True,

    "theme": "flatly",
    "dark_mode_theme": "darkly",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Ruta base del proyecto
STATIC_URL = '/static/'

# Directorios de archivos estáticos dentro del proyecto
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Ruta a la carpeta 'static' en el nivel del proyecto
]

# Carpeta donde se recopilan todos los archivos estáticos para producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media (para subida de archivos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
